### ISSUE TITLE
can't go to other dates from the "today" page

### ISSUE THREAD

**Issue by ajwcaltech** [gwpy/gwsumm#307]
If I go to https://ldas-jobs.ligo-wa.caltech.edu/~detchar/summary/today/ and then go to the date menu to select another date, it gives an "ERROR: Cannot format new date."

**Comment by eagoetz** [comment]
@ajwcaltech with apologies for the long delay responding to this since Alex left, the "today page" is a special page and is not typically reachable on the summary pages from the "landing page" https://ldas-jobs.ligo-wa.caltech.edu/~detchar/summary/

If I click on "today" I get to this page: https://ldas-jobs.ligo-wa.caltech.edu/~detchar/summary/day/20220721/. Then I can easily navigate to other day pages. @duncanmmacleod has programmed the summary pages to simply replace the YYYYMMDD string with the appropriate one for the new date.

I agree that it would be good if the calendar feature was smarter, but at this point, it is probably too much effort to make this work when folks can start from the landing page and click on various dates from there. I hope it's fine to close this issue.
