### ISSUE TITLE
documentation/user instructions seems to be out of date

### ISSUE THREAD

**Issue by shivarajkandhasamy** [gwpy/gwsumm#348]
The documentation in the link,
https://gwsumm.readthedocs.io/en/latest/
seems to be out of data and is missing contents. 

The working model example at the beginning doesn't work, it complains about no html,
`configparser.NoSectionError: No section: html`

I thought the [issue](https://github.com/gwpy/gwsumm/pull/80) fixed that. FYI, I am using conda environment available at the CIT cluster (igwn-py39) that provides gw_summary version 2.0.1.

**Comment by eagoetz** [comment]
@shivaraj17 Thanks for reporting this. Sadly, the documentation has been a low-priority item for a while now due to person power limitations. However, we will keep this in mind in case any spare cycles start to become available. I see that there are many broken things in the readthedocs pages.

I think it's best to start with the example shown in https://git.ligo.org/detchar/ligo-summary-pages/-/blob/master/CONTRIBUTING.md.
